name = "magister-marcus"
compatibility_date = "2024-01-01"

[[ratelimits]]
name = "CHAT_RATE_LIMITER"
namespace_id = "1001"

  [ratelimits.simple]
  limit = 20
  period = 10

[[kv_namespaces]]
binding = "PLANNER_KV"
id = "3850dd505ef04d3f8b2d0cb8c10d55b4"
